"""Create constructor standings table

Revision ID: 113fa539a85e
Revises: e5594efa2a41
Create Date: 2024-05-20 11:21:24.496911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113fa539a85e'
down_revision: Union[str, None] = 'e5594efa2a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'pit_stops', type_='foreignkey')
    op.drop_constraint(None, 'pit_stops', type_='foreignkey')
    op.drop_table('constructor_standings')
    # ### end Alembic commands ###
