"""create qualifying table

Revision ID: 8dc0e79f3ddc
Revises: 1f7e0a7b15c2
Create Date: 2024-05-20 05:55:31.047147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc0e79f3ddc'
down_revision: Union[str, None] = '1f7e0a7b15c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('races')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
