"""create driver standing table

Revision ID: e5594efa2a41
Revises: b9b5f9e11c61
Create Date: 2024-05-20 11:09:48.501700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5594efa2a41'
down_revision: Union[str, None] = 'b9b5f9e11c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'qualify', type_='foreignkey')
    op.drop_constraint(None, 'pit_stops', type_='foreignkey')
    op.drop_constraint(None, 'pit_stops', type_='foreignkey')
    # ### end Alembic commands ###
